### ISSUE TITLE
hi 

### ISSUE THREAD

**Issue by kkqu** [IgnacyWie/computer-science-2020-21#1]
**### _hi_** i have issue
pls help now
i downloaded it and now i have virus i need help now
ok?
![image](https://user-images.githubusercontent.com/48061679/108733039-6649f380-752e-11eb-94d0-edab8162ddfa.png)

**Comment by IgnacyWie** [comment]
Please close issue

**Comment by kkqu** [comment]
but my problem isnt solved
i still have virus

**Comment by IgnacyWie** [comment]
Just wear mask and everything will be okay
